// sims.js
const simData = [
    ["Abhogi", "Jaya Manohari", "Extra note N2 in avarohana"],
    ["Asaaveri", "Gana Murthi", "Sound so close why"],
    ["Begada", "NagaSwaraVali", ""],
    ["Bhoopalam", "Kalkada", "Why sound so similar"],
    ["Bahudaari", "NagaSwaraVali", ""],
    ["Brindavana Saranga", "Madhyamavathi", "G2 missing in Avarohana"],
    ["Bowli", "Reva Gupthi", "N3 missing in avarohana"],
    ["Dhenuka", "GanaMurthi", "G2 instead of G1"],
    ["Gurjari", "MayaMalavaGowla", "N3D1 instead of D1N3 in avarohanam"],
    ["Hindolam", "Jayanta Sri", "Avarohana extra note P"],
    ["Hindolam", "Maand", "G3, N3 instead of G2, N2"],
    ["Hindolam", "Suddha Dhanyasi", "Missing D1"],
    ["Hamsanandini", "Poorvee Kalyani", ""],
    ["Mukari", "Bhairavi", ""],
    ["Hemavati", "Simhendra Madhyamam", ""],
    ["Kadana Kutoohalam", "Bilahaari", "Avarohana"],
    ["Karahara Priya", "Sri Ranjani", "Only P missing"],
    ["Kamas", "Hari Kambhoji", "Asc. M1 replaced with R2"],
    ["KeeraNaavali", "Simhendra Madhyamam", "N3 missing in Avarohana in Keera"],
    ["Kalavathi", "SupraDeepam", "Extra note N3 in Aro and Avaro"],
    ["Kambhoji", "Hari Kambhoji", "N2 in Avarohanam"],
    ["Kambhoji", "SankaraBharanam", "Extra N3 in Aarohanam"],
    ["KamaVardhini", "PantuVarali", "Same as PantuVarali"],
    ["KamaVardhini", "DhathuVardhini", "Has R3 instead of R1"],
    ["Latangi", "Vaachaspati", "Differ in D2/D3"],
    ["Malaya Marutham", "Vlaji", "R1 missing in both phases"],
    ["Madhya MaaVathi", "Sree", "G2 missing in avarohana"],
    ["Maya Malava", "Paraju", "R1 missing in both phases"],
    ["ShanmukhaPriya", "SimhendraMadhyamam", "N2 instead of N3"],
    ["SimhendraMadhyamam", "Urmika", "D1 missing"]
];

